### ISSUE TITLE
Seems like this is all the fields in a table you need, are there any others?

### ISSUE THREAD

**Issue by joepagan** [pnomolos/arclightviewcart#1]
Thanks for this @pnomolos !!

From what I've found so far you need a table setup named `arclightviewcart_sessions`, with 3 fields/columns:
session_id - probs a varchar 255 will do?
session_data - probs a text will do?
updated_at - probs a varchar 255 will do?

**Comment by pnomolos** [comment]
@lexbi My .gitignore_global file had *.sql in it, so the SQL update files didn't get pushed with the rest of the code.  They've been added now :)

**Comment by joepagan** [comment]
Cheers dude.
